services:
  mongo:
    image: mongo:8
    container_name: mongo
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    depends_on:
      mongo:
        condition: service_healthy
