# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth/v1/auth.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'auth/v1/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from user.v1 import user_pb2 as user_dot_v1_dot_user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61uth/v1/auth.proto\x12\x07\x61uth.v1\x1a\x12user/v1/user.proto\"G\n\rSignUpRequest\x12\x1a\n\x08username\x18\x01 \x01(\tR\x08username\x12\x1a\n\x08password\x18\x02 \x01(\tR\x08password\"I\n\x0eSignUpResponse\x12!\n\x04user\x18\x01 \x01(\x0b\x32\r.user.v1.UserR\x04user\x12\x14\n\x05token\x18\x02 \x01(\tR\x05token\"F\n\x0cLoginRequest\x12\x1a\n\x08username\x18\x01 \x01(\tR\x08username\x12\x1a\n\x08password\x18\x02 \x01(\tR\x08password\"H\n\rLoginResponse\x12!\n\x04user\x18\x01 \x01(\x0b\x32\r.user.v1.UserR\x04user\x12\x14\n\x05token\x18\x02 \x01(\tR\x05token\",\n\x14ValidateTokenRequest\x12\x14\n\x05token\x18\x01 \x01(\tR\x05token\"P\n\x15ValidateTokenResponse\x12\x14\n\x05valid\x18\x01 \x01(\x08R\x05valid\x12!\n\x04user\x18\x02 \x01(\x0b\x32\r.user.v1.UserR\x04user2\xd0\x01\n\x0b\x41uthService\x12\x39\n\x06SignUp\x12\x16.auth.v1.SignUpRequest\x1a\x17.auth.v1.SignUpResponse\x12\x36\n\x05Login\x12\x15.auth.v1.LoginRequest\x1a\x16.auth.v1.LoginResponse\x12N\n\rValidateToken\x12\x1d.auth.v1.ValidateTokenRequest\x1a\x1e.auth.v1.ValidateTokenResponseB\x8e\x01\n\x0b\x63om.auth.v1B\tAuthProtoP\x01Z7github.com/provsalt/DOP_P01_Team1/common/auth/v1;authv1\xa2\x02\x03\x41XX\xaa\x02\x07\x41uth.V1\xca\x02\x07\x41uth\\V1\xe2\x02\x13\x41uth\\V1\\GPBMetadata\xea\x02\x08\x41uth::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth.v1.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\013com.auth.v1B\tAuthProtoP\001Z7github.com/provsalt/DOP_P01_Team1/common/auth/v1;authv1\242\002\003AXX\252\002\007Auth.V1\312\002\007Auth\\V1\342\002\023Auth\\V1\\GPBMetadata\352\002\010Auth::V1'
  _globals['_SIGNUPREQUEST']._serialized_start=51
  _globals['_SIGNUPREQUEST']._serialized_end=122
  _globals['_SIGNUPRESPONSE']._serialized_start=124
  _globals['_SIGNUPRESPONSE']._serialized_end=197
  _globals['_LOGINREQUEST']._serialized_start=199
  _globals['_LOGINREQUEST']._serialized_end=269
  _globals['_LOGINRESPONSE']._serialized_start=271
  _globals['_LOGINRESPONSE']._serialized_end=343
  _globals['_VALIDATETOKENREQUEST']._serialized_start=345
  _globals['_VALIDATETOKENREQUEST']._serialized_end=389
  _globals['_VALIDATETOKENRESPONSE']._serialized_start=391
  _globals['_VALIDATETOKENRESPONSE']._serialized_end=471
  _globals['_AUTHSERVICE']._serialized_start=474
  _globals['_AUTHSERVICE']._serialized_end=682
# @@protoc_insertion_point(module_scope)
