# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from file.v1 import file_pb2 as file_dot_v1_dot_file__pb2


class FileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateFile = channel.unary_unary(
                '/file.v1.FileService/CreateFile',
                request_serializer=file_dot_v1_dot_file__pb2.CreateFileRequest.SerializeToString,
                response_deserializer=file_dot_v1_dot_file__pb2.FileResponse.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/file.v1.FileService/ListFiles',
                request_serializer=file_dot_v1_dot_file__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=file_dot_v1_dot_file__pb2.ListFilesResponse.FromString,
                _registered_method=True)
        self.GetFile = channel.unary_unary(
                '/file.v1.FileService/GetFile',
                request_serializer=file_dot_v1_dot_file__pb2.GetFileRequest.SerializeToString,
                response_deserializer=file_dot_v1_dot_file__pb2.FileResponse.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/file.v1.FileService/DeleteFile',
                request_serializer=file_dot_v1_dot_file__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=file_dot_v1_dot_file__pb2.DeleteFileResponse.FromString,
                _registered_method=True)


class FileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateFile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFile,
                    request_deserializer=file_dot_v1_dot_file__pb2.CreateFileRequest.FromString,
                    response_serializer=file_dot_v1_dot_file__pb2.FileResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=file_dot_v1_dot_file__pb2.ListFilesRequest.FromString,
                    response_serializer=file_dot_v1_dot_file__pb2.ListFilesResponse.SerializeToString,
            ),
            'GetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=file_dot_v1_dot_file__pb2.GetFileRequest.FromString,
                    response_serializer=file_dot_v1_dot_file__pb2.FileResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=file_dot_v1_dot_file__pb2.DeleteFileRequest.FromString,
                    response_serializer=file_dot_v1_dot_file__pb2.DeleteFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'file.v1.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('file.v1.FileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file.v1.FileService/CreateFile',
            file_dot_v1_dot_file__pb2.CreateFileRequest.SerializeToString,
            file_dot_v1_dot_file__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file.v1.FileService/ListFiles',
            file_dot_v1_dot_file__pb2.ListFilesRequest.SerializeToString,
            file_dot_v1_dot_file__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file.v1.FileService/GetFile',
            file_dot_v1_dot_file__pb2.GetFileRequest.SerializeToString,
            file_dot_v1_dot_file__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file.v1.FileService/DeleteFile',
            file_dot_v1_dot_file__pb2.DeleteFileRequest.SerializeToString,
            file_dot_v1_dot_file__pb2.DeleteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
