# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from file.v1 import file_pb2 as file_dot_v1_dot_file__pb2


class FileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFile = channel.stream_unary(
                '/file.v1.FileService/UploadFile',
                request_serializer=file_dot_v1_dot_file__pb2.UploadFileRequest.SerializeToString,
                response_deserializer=file_dot_v1_dot_file__pb2.FileResponse.FromString,
                _registered_method=True)
        self.CreateFile = channel.unary_unary(
                '/file.v1.FileService/CreateFile',
                request_serializer=file_dot_v1_dot_file__pb2.CreateFileRequest.SerializeToString,
                response_deserializer=file_dot_v1_dot_file__pb2.FileResponse.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/file.v1.FileService/ListFiles',
                request_serializer=file_dot_v1_dot_file__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=file_dot_v1_dot_file__pb2.ListFilesResponse.FromString,
                _registered_method=True)
        self.GetFile = channel.unary_unary(
                '/file.v1.FileService/GetFile',
                request_serializer=file_dot_v1_dot_file__pb2.GetFileRequest.SerializeToString,
                response_deserializer=file_dot_v1_dot_file__pb2.FileResponse.FromString,
                _registered_method=True)
        self.DownloadFile = channel.unary_stream(
                '/file.v1.FileService/DownloadFile',
                request_serializer=file_dot_v1_dot_file__pb2.DownloadFileRequest.SerializeToString,
                response_deserializer=file_dot_v1_dot_file__pb2.DownloadFileResponse.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/file.v1.FileService/DeleteFile',
                request_serializer=file_dot_v1_dot_file__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=file_dot_v1_dot_file__pb2.DeleteFileResponse.FromString,
                _registered_method=True)
        self.InitiateMultipartUpload = channel.unary_unary(
                '/file.v1.FileService/InitiateMultipartUpload',
                request_serializer=file_dot_v1_dot_file__pb2.InitiateMultipartUploadRequest.SerializeToString,
                response_deserializer=file_dot_v1_dot_file__pb2.InitiateMultipartUploadResponse.FromString,
                _registered_method=True)
        self.UploadPart = channel.unary_unary(
                '/file.v1.FileService/UploadPart',
                request_serializer=file_dot_v1_dot_file__pb2.UploadPartRequest.SerializeToString,
                response_deserializer=file_dot_v1_dot_file__pb2.UploadPartResponse.FromString,
                _registered_method=True)
        self.CompleteMultipartUpload = channel.unary_unary(
                '/file.v1.FileService/CompleteMultipartUpload',
                request_serializer=file_dot_v1_dot_file__pb2.CompleteMultipartUploadRequest.SerializeToString,
                response_deserializer=file_dot_v1_dot_file__pb2.FileResponse.FromString,
                _registered_method=True)
        self.AbortMultipartUpload = channel.unary_unary(
                '/file.v1.FileService/AbortMultipartUpload',
                request_serializer=file_dot_v1_dot_file__pb2.AbortMultipartUploadRequest.SerializeToString,
                response_deserializer=file_dot_v1_dot_file__pb2.AbortMultipartUploadResponse.FromString,
                _registered_method=True)


class FileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitiateMultipartUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadPart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteMultipartUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortMultipartUpload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=file_dot_v1_dot_file__pb2.UploadFileRequest.FromString,
                    response_serializer=file_dot_v1_dot_file__pb2.FileResponse.SerializeToString,
            ),
            'CreateFile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFile,
                    request_deserializer=file_dot_v1_dot_file__pb2.CreateFileRequest.FromString,
                    response_serializer=file_dot_v1_dot_file__pb2.FileResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=file_dot_v1_dot_file__pb2.ListFilesRequest.FromString,
                    response_serializer=file_dot_v1_dot_file__pb2.ListFilesResponse.SerializeToString,
            ),
            'GetFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFile,
                    request_deserializer=file_dot_v1_dot_file__pb2.GetFileRequest.FromString,
                    response_serializer=file_dot_v1_dot_file__pb2.FileResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=file_dot_v1_dot_file__pb2.DownloadFileRequest.FromString,
                    response_serializer=file_dot_v1_dot_file__pb2.DownloadFileResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=file_dot_v1_dot_file__pb2.DeleteFileRequest.FromString,
                    response_serializer=file_dot_v1_dot_file__pb2.DeleteFileResponse.SerializeToString,
            ),
            'InitiateMultipartUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiateMultipartUpload,
                    request_deserializer=file_dot_v1_dot_file__pb2.InitiateMultipartUploadRequest.FromString,
                    response_serializer=file_dot_v1_dot_file__pb2.InitiateMultipartUploadResponse.SerializeToString,
            ),
            'UploadPart': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadPart,
                    request_deserializer=file_dot_v1_dot_file__pb2.UploadPartRequest.FromString,
                    response_serializer=file_dot_v1_dot_file__pb2.UploadPartResponse.SerializeToString,
            ),
            'CompleteMultipartUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteMultipartUpload,
                    request_deserializer=file_dot_v1_dot_file__pb2.CompleteMultipartUploadRequest.FromString,
                    response_serializer=file_dot_v1_dot_file__pb2.FileResponse.SerializeToString,
            ),
            'AbortMultipartUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortMultipartUpload,
                    request_deserializer=file_dot_v1_dot_file__pb2.AbortMultipartUploadRequest.FromString,
                    response_serializer=file_dot_v1_dot_file__pb2.AbortMultipartUploadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'file.v1.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('file.v1.FileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/file.v1.FileService/UploadFile',
            file_dot_v1_dot_file__pb2.UploadFileRequest.SerializeToString,
            file_dot_v1_dot_file__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file.v1.FileService/CreateFile',
            file_dot_v1_dot_file__pb2.CreateFileRequest.SerializeToString,
            file_dot_v1_dot_file__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file.v1.FileService/ListFiles',
            file_dot_v1_dot_file__pb2.ListFilesRequest.SerializeToString,
            file_dot_v1_dot_file__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file.v1.FileService/GetFile',
            file_dot_v1_dot_file__pb2.GetFileRequest.SerializeToString,
            file_dot_v1_dot_file__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/file.v1.FileService/DownloadFile',
            file_dot_v1_dot_file__pb2.DownloadFileRequest.SerializeToString,
            file_dot_v1_dot_file__pb2.DownloadFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file.v1.FileService/DeleteFile',
            file_dot_v1_dot_file__pb2.DeleteFileRequest.SerializeToString,
            file_dot_v1_dot_file__pb2.DeleteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitiateMultipartUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file.v1.FileService/InitiateMultipartUpload',
            file_dot_v1_dot_file__pb2.InitiateMultipartUploadRequest.SerializeToString,
            file_dot_v1_dot_file__pb2.InitiateMultipartUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadPart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file.v1.FileService/UploadPart',
            file_dot_v1_dot_file__pb2.UploadPartRequest.SerializeToString,
            file_dot_v1_dot_file__pb2.UploadPartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteMultipartUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file.v1.FileService/CompleteMultipartUpload',
            file_dot_v1_dot_file__pb2.CompleteMultipartUploadRequest.SerializeToString,
            file_dot_v1_dot_file__pb2.FileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortMultipartUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/file.v1.FileService/AbortMultipartUpload',
            file_dot_v1_dot_file__pb2.AbortMultipartUploadRequest.SerializeToString,
            file_dot_v1_dot_file__pb2.AbortMultipartUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
