# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from user.v1 import user_pb2 as user_dot_v1_dot_user__pb2


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/user.v1.UserService/CreateUser',
                request_serializer=user_dot_v1_dot_user__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.CreateUserResponse.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/user.v1.UserService/GetUser',
                request_serializer=user_dot_v1_dot_user__pb2.GetUserRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.GetUserResponse.FromString,
                _registered_method=True)
        self.GetUserByUsername = channel.unary_unary(
                '/user.v1.UserService/GetUserByUsername',
                request_serializer=user_dot_v1_dot_user__pb2.GetUserByUsernameRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.GetUserByUsernameResponse.FromString,
                _registered_method=True)
        self.VerifyPassword = channel.unary_unary(
                '/user.v1.UserService/VerifyPassword',
                request_serializer=user_dot_v1_dot_user__pb2.VerifyPasswordRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.VerifyPasswordResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/user.v1.UserService/DeleteUser',
                request_serializer=user_dot_v1_dot_user__pb2.DeleteUserByIdRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.DeleteUserByIdResponse.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/user.v1.UserService/ListUsers',
                request_serializer=user_dot_v1_dot_user__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.ListUsersResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByUsername(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyPassword(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=user_dot_v1_dot_user__pb2.CreateUserRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.CreateUserResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=user_dot_v1_dot_user__pb2.GetUserRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.GetUserResponse.SerializeToString,
            ),
            'GetUserByUsername': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByUsername,
                    request_deserializer=user_dot_v1_dot_user__pb2.GetUserByUsernameRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.GetUserByUsernameResponse.SerializeToString,
            ),
            'VerifyPassword': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyPassword,
                    request_deserializer=user_dot_v1_dot_user__pb2.VerifyPasswordRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.VerifyPasswordResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=user_dot_v1_dot_user__pb2.DeleteUserByIdRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.DeleteUserByIdResponse.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=user_dot_v1_dot_user__pb2.ListUsersRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.ListUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.v1.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('user.v1.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/CreateUser',
            user_dot_v1_dot_user__pb2.CreateUserRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/GetUser',
            user_dot_v1_dot_user__pb2.GetUserRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.GetUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserByUsername(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/GetUserByUsername',
            user_dot_v1_dot_user__pb2.GetUserByUsernameRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.GetUserByUsernameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyPassword(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/VerifyPassword',
            user_dot_v1_dot_user__pb2.VerifyPasswordRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.VerifyPasswordResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/DeleteUser',
            user_dot_v1_dot_user__pb2.DeleteUserByIdRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.DeleteUserByIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/ListUsers',
            user_dot_v1_dot_user__pb2.ListUsersRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
